# scripts/02a-figure1-motivating-example.R
# Figure 1: motivating example.
# One 2-AFC dataset, several plausible fitted models, and different
# interaction conclusions generated by different link assumptions.

rm(list = ls())

if (!requireNamespace("ggplot2", quietly = TRUE)) {
  stop("Please install ggplot2.", call. = FALSE)
}

source("R/project-settings.R")
source("R/utils-reporting.R")
source("R/utils-link-functions.R")
source("R/utils-plots.R")

ensure_output_dirs()

report_header("Figure 1 motivating example")

# ---------------------------------------------------------------------
# 1. Local settings and scenario
# ---------------------------------------------------------------------
# Values in this block define this specific figure. They should remain in
# this script, not in R/project-settings.R.

settings <- list(
  table_scenario_path = "tables/scenario-table-fig1-motivating-example.csv",
  table_models_path = "tables/model-results-fig1-motivating-example.csv",
  figure_base = "figs/fig1-motivating-example",
  rds_path = "outputs/fig1-motivating-example.rds",
  seed = 20260524
)

scenario <- list(
  name = "2-AFC chance-floor motivating example",
  N = 1000,
  k_trials = 50,
  chance = 0.50,
  age_range = c(6, 10),
  age_center = 8,
  beta_intercept = 0.00,
  beta_age = 1.00,
  beta_group = -1.40,
  beta_age_group = 0.00,
  generating_link = "logit"
)

# Local summary and plotting values. These are derived from the scenario
# so that tables and figures remain consistent if age_range or age_center change.
scenario$age_summary_values <- c(
  scenario$age_range[1],
  scenario$age_center,
  scenario$age_range[2]
)
scenario$age_plot_values <- seq(
  scenario$age_range[1],
  scenario$age_range[2],
  length.out = 240
)

scenario$age_bin_breaks <- seq(
  scenario$age_range[1],
  scenario$age_range[2],
  length.out = 9
)

validate_scenario <- function(s) {
  required <- c(
    "N", "k_trials", "chance", "age_range", "age_center",
    "beta_intercept", "beta_age", "beta_group", "beta_age_group",
    "generating_link", "age_summary_values", "age_plot_values", "age_bin_breaks"
  )
  missing <- setdiff(required, names(s))
  if (length(missing) > 0) {
    stop("Missing scenario values: ", paste(missing, collapse = ", "), call. = FALSE)
  }
  
  if (!is.numeric(s$age_range) || length(s$age_range) != 2 || s$age_range[1] >= s$age_range[2]) {
    stop("scenario$age_range must be an increasing numeric vector of length 2.", call. = FALSE)
  }
  if (!is.finite(s$age_center) || s$age_center < s$age_range[1] || s$age_center > s$age_range[2]) {
    stop("scenario$age_center must be inside scenario$age_range.", call. = FALSE)
  }
  if (!is.finite(s$chance) || s$chance < 0 || s$chance >= 1) {
    stop("scenario$chance must be in [0, 1).", call. = FALSE)
  }
  if (!is.finite(s$N) || s$N < 1 || s$N != as.integer(s$N)) {
    stop("scenario$N must be a positive integer.", call. = FALSE)
  }
  if (!is.finite(s$k_trials) || s$k_trials < 1 || s$k_trials != as.integer(s$k_trials)) {
    stop("scenario$k_trials must be a positive integer.", call. = FALSE)
  }
  
  check_supported_link(s$generating_link)
  invisible(s)
}

validate_scenario(scenario)
set.seed(settings$seed)

report_section("Scenario parameters you can tune")
scenario_report <- scenario[setdiff(names(scenario), c("age_plot_values", "age_bin_breaks"))]
print_compact(list_to_table(scenario_report))
cat("\nTuning guide:\n")
cat("- beta_intercept moves the whole scenario toward the floor or ceiling.\n")
cat("- beta_age controls the age trend on the generating link scale.\n")
cat("- beta_group controls the group gap on the generating link scale.\n")
cat("- chance = .50 gives a 2-AFC lower asymptote. Use .25 for 4-AFC.\n")
cat("- beta_age_group is fixed at 0 here, so the true link-scale interaction is absent.\n")

# ---------------------------------------------------------------------
# 2. Data-generating functions
# ---------------------------------------------------------------------

eta_fun <- function(age, group_num) {
  age_c <- age - scenario$age_center
  scenario$beta_intercept +
    scenario$beta_age * age_c +
    scenario$beta_group * group_num +
    scenario$beta_age_group * age_c * group_num
}

p_fun <- function(age, group_num) {
  chance_linkinv(
    eta_fun(age, group_num),
    chance = scenario$chance,
    link = scenario$generating_link
  )
}

group_factor <- function(group_num) {
  factor(
    group_num,
    levels = c(0, 1),
    labels = c("Group 0", "Group 1")
  )
}

# ---------------------------------------------------------------------
# 3. Scenario table: implied values and contrasts
# ---------------------------------------------------------------------

summary_grid <- expand.grid(
  age = scenario$age_summary_values,
  group_num = c(0, 1)
)
summary_grid$group <- group_factor(summary_grid$group_num)
summary_grid$eta <- eta_fun(summary_grid$age, summary_grid$group_num)
summary_grid$expected_accuracy <- p_fun(summary_grid$age, summary_grid$group_num)
summary_grid$expected_correct_out_of_k_trials <-
  summary_grid$expected_accuracy * scenario$k_trials

scenario_values <- data.frame(
  scenario = scenario$name,
  age = summary_grid$age,
  group = summary_grid$group,
  linear_predictor = summary_grid$eta,
  expected_accuracy = summary_grid$expected_accuracy,
  expected_correct_out_of_k_trials = summary_grid$expected_correct_out_of_k_trials,
  stringsAsFactors = FALSE
)

age_low <- scenario$age_range[1]
age_high <- scenario$age_range[2]

p_low_g0 <- p_fun(age_low, 0)
p_low_g1 <- p_fun(age_low, 1)
p_high_g0 <- p_fun(age_high, 0)
p_high_g1 <- p_fun(age_high, 1)

scenario_contrasts <- data.frame(
  scenario = scenario$name,
  contrast = c(
    "Group difference at youngest age: Group 1 minus Group 0",
    "Group difference at oldest age: Group 1 minus Group 0",
    "Age-related change in Group 0: oldest minus youngest",
    "Age-related change in Group 1: oldest minus youngest",
    "Change in group difference from youngest to oldest age",
    "Generating link-scale age-by-group product term"
  ),
  value_probability_points = c(
    group_difference(p_low_g0, p_low_g1),
    group_difference(p_high_g0, p_high_g1),
    p_high_g0 - p_low_g0,
    p_high_g1 - p_low_g1,
    change_in_group_difference(p_low_g0, p_low_g1, p_high_g0, p_high_g1),
    NA_real_
  ),
  link_scale_value = c(NA, NA, NA, NA, NA, scenario$beta_age_group),
  stringsAsFactors = FALSE
)
scenario_contrasts$value_correct_out_of_k_trials <-
  scenario_contrasts$value_probability_points * scenario$k_trials

scenario_table <- rbind(
  data.frame(
    table_part = "implied_values",
    scenario_values,
    contrast = NA_character_,
    value_probability_points = NA_real_,
    value_correct_out_of_k_trials = NA_real_,
    link_scale_value = NA_real_,
    stringsAsFactors = FALSE
  ),
  data.frame(
    table_part = "derived_contrasts",
    scenario = scenario_contrasts$scenario,
    age = NA_real_,
    group = NA_character_,
    linear_predictor = NA_real_,
    expected_accuracy = NA_real_,
    expected_correct_out_of_k_trials = NA_real_,
    contrast = scenario_contrasts$contrast,
    value_probability_points = scenario_contrasts$value_probability_points,
    value_correct_out_of_k_trials = scenario_contrasts$value_correct_out_of_k_trials,
    link_scale_value = scenario_contrasts$link_scale_value,
    stringsAsFactors = FALSE
  )
)

utils::write.csv(scenario_table, settings$table_scenario_path, row.names = FALSE)

report_section("Implied scenario values")
print_compact(scenario_values)
report_section("Derived contrasts implied by the scenario")
print_compact(scenario_contrasts)
report_sign_convention(paste0("age ", age_low), paste0("age ", age_high))

# ---------------------------------------------------------------------
# 4. Simulate one illustrative dataset
# ---------------------------------------------------------------------

group_num <- stats::rbinom(scenario$N, 1, 0.5)
age <- stats::runif(scenario$N, scenario$age_range[1], scenario$age_range[2])
age_c <- age - scenario$age_center
eta <- eta_fun(age, group_num)
prob <- p_fun(age, group_num)
y <- stats::rbinom(scenario$N, size = scenario$k_trials, prob = prob)

d <- data.frame(
  age = age,
  age_c = age_c,
  group_num = group_num,
  group = group_factor(group_num),
  y = y,
  k = scenario$k_trials,
  accuracy = y / scenario$k_trials
)

report_section("One simulated dataset")
cat("Observed mean accuracy by group:\n")
print_compact(stats::aggregate(accuracy ~ group, d, mean))

# ---------------------------------------------------------------------
# 5. Fit candidate models
# ---------------------------------------------------------------------

fit_identity <- stats::lm(accuracy ~ age_c * group, data = d)
fit_logit <- stats::glm(
  cbind(y, k - y) ~ age_c * group,
  family = stats::binomial("logit"),
  data = d
)
fit_probit <- stats::glm(
  cbind(y, k - y) ~ age_c * group,
  family = stats::binomial("probit"),
  data = d
)
fit_chance <- fit_chance_binom(
  ~ age_c * group,
  data = d,
  y_col = "y",
  k_col = "k",
  chance = scenario$chance,
  link = scenario$generating_link
)

model_names <- c(
  "Identity",
  "Standard logit",
  "Standard probit",
  "Chance-corrected logit"
)

# Keep the figure visually simple while retaining all four models in the table.
plot_model_names <- c(
  "Identity",
  "Standard logit",
  "Chance-corrected logit"
)

predict_model <- function(model_name, newdata) {
  if (model_name == "Identity") {
    return(stats::predict(fit_identity, newdata = newdata))
  }
  if (model_name == "Standard logit") {
    return(stats::predict(fit_logit, newdata = newdata, type = "response"))
  }
  if (model_name == "Standard probit") {
    return(stats::predict(fit_probit, newdata = newdata, type = "response"))
  }
  if (model_name == "Chance-corrected logit") {
    return(predict_chance_binom(fit_chance, newdata = newdata, type = "response"))
  }
  stop("Unknown model: ", model_name, call. = FALSE)
}

model_results <- data.frame(
  model = model_names,
  interaction_coef = c(
    interaction_coef_from_lm(fit_identity),
    interaction_coef_from_glm(fit_logit),
    interaction_coef_from_glm(fit_probit),
    interaction_coef_from_chance(fit_chance)
  ),
  p_value = c(
    interaction_p_from_lm(fit_identity),
    interaction_p_from_glm(fit_logit),
    interaction_p_from_glm(fit_probit),
    interaction_p_from_chance(fit_chance)
  ),
  stringsAsFactors = FALSE
)

# Model-implied change in the predicted group difference on the response scale.
contrast_grid <- expand.grid(
  age = c(age_low, age_high),
  group = factor(c("Group 0", "Group 1"), levels = c("Group 0", "Group 1"))
)
contrast_grid$age_c <- contrast_grid$age - scenario$age_center

for (m in model_names) {
  pred <- predict_model(m, contrast_grid)
  
  m_low_g0 <- pred[contrast_grid$age == age_low & contrast_grid$group == "Group 0"]
  m_low_g1 <- pred[contrast_grid$age == age_low & contrast_grid$group == "Group 1"]
  m_high_g0 <- pred[contrast_grid$age == age_high & contrast_grid$group == "Group 0"]
  m_high_g1 <- pred[contrast_grid$age == age_high & contrast_grid$group == "Group 1"]
  
  model_results$change_in_group_difference_probability_points[model_results$model == m] <-
    change_in_group_difference(m_low_g0, m_low_g1, m_high_g0, m_high_g1)
  
  model_results$change_in_group_difference_correct_out_of_k_trials[model_results$model == m] <-
    model_results$change_in_group_difference_probability_points[model_results$model == m] *
    scenario$k_trials
}

utils::write.csv(model_results, settings$table_models_path, row.names = FALSE)

report_section("Model conclusions for the same dataset")
print_compact(model_results)
cat("\nInterpretation aid: change_in_group_difference_correct_out_of_k_trials is not an observed count.\n")
cat(
  "It is the model-implied change in the predicted group difference from age ",
  age_low, " to age ", age_high, ",\n",
  sep = ""
)
cat("expressed as correct-response units out of ", scenario$k_trials, " trials.\n", sep = "")

# ---------------------------------------------------------------------
# 6. Figure panels
# ---------------------------------------------------------------------

plot_grid <- expand.grid(
  age = scenario$age_plot_values,
  group_num = c(0, 1)
)
plot_grid$group <- group_factor(plot_grid$group_num)
plot_grid$age_c <- plot_grid$age - scenario$age_center
plot_grid$expected_accuracy <- p_fun(plot_grid$age, plot_grid$group_num)

# For the figure, show the no-product-term baselines implied by each model.
# The interaction models fitted above are retained for the model-results table.
fit_identity_additive <- stats::lm(accuracy ~ age_c + group, data = d)

fit_logit_additive <- stats::glm(
  cbind(y, k - y) ~ age_c + group,
  family = stats::binomial("logit"),
  data = d
)

fit_chance_additive <- fit_chance_binom(
  ~ age_c + group,
  data = d,
  y_col = "y",
  k_col = "k",
  chance = scenario$chance,
  link = scenario$generating_link
)

baseline_model_names <- c(
  "Gaussian identity",
  "Standard binomial logit",
  "Chance-corrected binomial"
)

predict_baseline <- function(model_name, newdata) {
  if (model_name == "Gaussian identity") {
    return(stats::predict(fit_identity_additive, newdata = newdata))
  }
  
  if (model_name == "Standard binomial logit") {
    return(stats::predict(fit_logit_additive, newdata = newdata, type = "response"))
  }
  
  if (model_name == "Chance-corrected binomial") {
    return(predict_chance_binom(fit_chance_additive, newdata = newdata, type = "response"))
  }
  
  stop("Unknown baseline model: ", model_name, call. = FALSE)
}

baseline_long <- do.call(
  rbind,
  lapply(baseline_model_names, function(m) {
    data.frame(
      age = plot_grid$age,
      group = plot_grid$group,
      model = m,
      predicted = predict_baseline(m, plot_grid),
      stringsAsFactors = FALSE
    )
  })
)

baseline_long$model <- factor(baseline_long$model, levels = baseline_model_names)
baseline_long$model_label <- factor(
  baseline_long$model,
  levels = baseline_model_names,
  labels = c(
    "Gaussian identity",
    "Standard binomial logit",
    "Chance-corrected binomial link"
  )
)

# Binned data for readability. The same binned points are repeated in each facet.
d$age_bin <- cut(d$age, breaks = scenario$age_bin_breaks, include.lowest = TRUE)
binned <- stats::aggregate(accuracy ~ age_bin + group, d, mean)
binned$age_mid <- bin_midpoints(binned$age_bin)

binned_facets <- merge(
  binned,
  data.frame(model_label = levels(baseline_long$model_label)),
  by = NULL
)

binned_facets$model_label <- factor(
  binned_facets$model_label,
  levels = levels(baseline_long$model_label)
)

# Light construction lines in Panel A: equal one-year age steps are equal
# steps on eta because beta_age = 1 and beta_age_group = 0, but not equal
# steps on the observed accuracy scale.
step_ages <- seq(
  scenario$age_range[1],
  scenario$age_range[2],
  by = 1
)

step_df <- data.frame(
  age = step_ages,
  group = group_factor(0),
  expected_accuracy = p_fun(step_ages, 0)
)

step_h <- data.frame(
  x = min(scenario$age_plot_values),
  xend = step_df$age,
  y = step_df$expected_accuracy,
  yend = step_df$expected_accuracy
)

step_v <- data.frame(
  x = step_df$age,
  xend = step_df$age,
  y = scenario$chance,
  yend = step_df$expected_accuracy
)

floor_rect <- data.frame(
  xmin = -Inf,
  xmax = Inf,
  ymin = -Inf,
  ymax = scenario$chance
)

p1 <- ggplot2::ggplot(
  plot_grid,
  ggplot2::aes(age, expected_accuracy, color = group, linetype = group)
) +
  ggplot2::geom_rect(
    data = floor_rect,
    ggplot2::aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
    inherit.aes = FALSE,
    fill = "grey95",
    color = NA
  ) +
  ggplot2::geom_segment(
    data = step_h,
    ggplot2::aes(x = x, xend = xend, y = y, yend = yend),
    inherit.aes = FALSE,
    linewidth = 0.25,
    color = "grey70"
  ) +
  ggplot2::geom_segment(
    data = step_v,
    ggplot2::aes(x = x, xend = xend, y = y, yend = yend),
    inherit.aes = FALSE,
    linewidth = 0.25,
    color = "grey70"
  ) +
  ggplot2::geom_hline(
    yintercept = scenario$chance,
    linewidth = 0.45,
    linetype = "dotted",
    color = "grey30"
  ) +
  ggplot2::geom_line(linewidth = 1.0) +
  ggplot2::geom_point(
    data = step_df,
    ggplot2::aes(age, expected_accuracy),
    inherit.aes = FALSE,
    size = 1.6,
    color = "grey25"
  ) +
  ggplot2::coord_cartesian(ylim = c(scenario$chance - 0.02, 1.02)) +
  ggplot2::scale_y_continuous(
    breaks = c(0.50, 0.60, 0.75, 0.90, 1.00),
    labels = percent_labels()
  ) +
  link_scale_color_discrete(name = "Group") +
  link_scale_linetype_discrete(name = "Group") +
  ggplot2::labs(
    title = "A. Data-generating pattern",
    subtitle = "No age-by-group term on the chance-corrected 2-AFC scale",
    x = "Age",
    y = "Expected accuracy"
  ) +
  link_theme(base_size = 10.5)

p2 <- ggplot2::ggplot() +
  ggplot2::geom_rect(
    data = floor_rect,
    ggplot2::aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
    inherit.aes = FALSE,
    fill = "grey95",
    color = NA
  ) +
  ggplot2::geom_hline(
    yintercept = scenario$chance,
    linewidth = 0.45,
    linetype = "dotted",
    color = "grey30"
  ) +
  ggplot2::geom_point(
    data = binned_facets,
    ggplot2::aes(age_mid, accuracy, color = group, shape = group),
    size = 1.9,
    alpha = 0.85
  ) +
  ggplot2::geom_line(
    data = baseline_long,
    ggplot2::aes(age, predicted, color = group, linetype = group),
    linewidth = 0.9
  ) +
  ggplot2::facet_wrap(~ model_label, ncol = 3) +
  ggplot2::coord_cartesian(ylim = c(0.30, 1.02)) +
  ggplot2::scale_y_continuous(
    breaks = c(0.30, 0.50, 0.70, 0.90, 1.00),
    labels = percent_labels()
  ) +
  link_scale_color_discrete(name = "Group") +
  link_scale_linetype_discrete(name = "Group") +
  link_scale_shape_discrete(name = "Group") +
  ggplot2::labs(
    title = "B. Same binned data, different no-interaction baselines",
    subtitle = "Each facet fits an additive model on a different scale",
    x = "Age",
    y = "Accuracy"
  ) +
  link_theme(base_size = 9.5) +
  ggplot2::theme(
    legend.position = "bottom",
    strip.text = ggplot2::element_text(size = 8.8, face = "bold")
  )

save_plot_grid(
  list(p1, p2),
  filename_base = settings$figure_base,
  width = figure_width,
  height = 6.4,
  ncol = 1,
  dpi = default_dpi
)


# SAVE OUTPUT #

save_plot_grid(
  list(p1, p2),
  filename_base = settings$figure_base,
  width = figure_width,
  height = 7.2,
  ncol = 1,
  dpi = default_dpi
)

saveRDS(
  list(
    settings = settings,
    scenario_parameters = scenario,
    scenario_table = scenario_table,
    example_dataset = d,
    model_results_example = model_results,
    predictions = baseline_long,
    fits = list(
      identity = fit_identity,
      logit = fit_logit,
      probit = fit_probit,
      chance_logit = fit_chance,
      identity_additive = fit_identity_additive,
      logit_additive = fit_logit_additive,
      chance_logit_additive = fit_chance_additive
    )
  ),
  file = settings$rds_path
)

report_section("Saved files")
cat("- ", settings$table_scenario_path, "\n", sep = "")
cat("- ", settings$table_models_path, "\n", sep = "")
cat("- ", settings$figure_base, ".pdf/png\n", sep = "")
cat("- ", settings$rds_path, "\n", sep = "")
cat("\nDone.\n")
